version: "3.5"
services:
  centos7ftptray:
    volumes:
      - rpm7:/home/centos/rpmbuild/RPMS
    build:
      context: createrepo
      dockerfile: Dockerfile.ftptray
      args:
        centos: $OS7
    image: aursu/rpmbuild:ftptray
  centos8ftptray:
    volumes:
      - rpm8:/home/centos/rpmbuild/RPMS
    image: aursu/rpmbuild:ftptray
  ftprepo:
    volumes:
      - rpm7:/home/centos-7/rpmbuild/RPMS
      - rpm8:/home/centos-8/rpmbuild/RPMS
    build:
      context: ftprepo
    image: aursu/rpmbuild:ftprepo
    ports:
      - "21:21"
      - "49152-49160:49152-49160"
    environment:
      - PUBLICADDR
      - PROFTPD_OPTIONS

volumes:
  rpm7:
    name: rpm7
  rpm8:
    name: rpm8
