version: "3.5"
services:
  centos7basesystemd:
    build:
      context: 7/base
      dockerfile: Dockerfile.systemd
      args:
        centos: $OS7
    image: "aursu/rpmbuild:${OS7TAG}-base-systemd"
  stream8basesystemd:
    build:
      context: 8-stream/base
      args:
        image: systemd
    image: aursu/rpmbuild:stream8-base-systemd
  stream9basesystemd:
    build:
      context: 9-stream/base
      args:
        centos: $OS9
        image: systemd
    image: "aursu/rpmbuild:${OS9TAG}-base-systemd"
  centos7buildsystemd:
    build:
      context: 7/build
      dockerfile: Dockerfile.systemd
      args:
        centos: $OS7
    image: "aursu/rpmbuild:${OS7TAG}-build-systemd"
  stream8buildsystemd:
    build:
      context: 8-stream/build
      args:
        centos: stream8
        image: base-systemd
    image: aursu/rpmbuild:stream8-build-systemd
  stream9buildsystemd:
    build:
      context: 9-stream/build
      args:
        centos: $OS9
        image: base-systemd
    image: "aursu/rpmbuild:${OS9TAG}-build-systemd"
  centos7buildtest:
    networks:
      - buildnet
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp=unconfined
    tmpfs:
      - /run
    image: "aursu/rpmbuild:${OS7}-build-systemd"
  stream8buildtest:
    networks:
      - buildnet
    privileged: true
    cgroup_parent: docker.slice
    tmpfs:
      - /run
      - /tmp
    image: aursu/rpmbuild:stream8-build-systemd

networks:
  buildnet:
    name: buildnet
