version: "3"
services:
  base:
    build:
      context: 7/base
    image: rpmbuild:7-base
  rpmbuild:
    build:
      context: 7/build
    image: rpmbuild:7-build
  webrepo:
    volumes:
      - rpm6:/home/centos-6/rpmbuild/RPMS
      - rpm7:/home/centos-7/rpmbuild/RPMS
    build:
      context: webrepo
    image: rpmbuild:webrepo

volumes:
  rpm6:
  rpm7:
