version: "3.5"
services:
  centos6base:
    build:
      context: 6/base
      args:
        centos: $OS6
    image: "aursu/rpmbuild:${OS6TAG}-base"
  centos7base:
    build:
      context: 7/base
      args:
        centos: $OS7
    image: "aursu/rpmbuild:${OS7TAG}-base"
  centos7baseroot:
    build:
      context: 7/base
      dockerfile: Dockerfile.root
      args:
        centos: $OS7
    image: "aursu/rpmbuild:${OS7TAG}-base-root"
  centos8base:
    build:
      context: 8/base
      args:
        centos: $OS8
    image: "aursu/rpmbuild:${OS8TAG}-base"
  centos8baseroot:
    build:
      context: 8/base
      dockerfile: Dockerfile.root
      args:
        centos: $OS8
    image: "aursu/rpmbuild:${OS8TAG}-base-root"
  centos6build:
    build:
      context: 6/build
      args:
        centos: $OS6
    image: "aursu/rpmbuild:${OS6TAG}-build"
  centos7build:
    build:
      context: 7/build
      args:
        centos: $OS7
    image: "aursu/rpmbuild:${OS7TAG}-build"
  centos7buildroot:
    build:
      context: 7/build
      args:
        centos: $OS7
        image: base-root
    image: "aursu/rpmbuild:${OS7TAG}-build-root"
  centos8build:
    build:
      context: 8/build
      args:
        centos: $OS8
    image: "aursu/rpmbuild:${OS8TAG}-build"
  centos8buildroot:
    build:
      context: 8/build
      args:
        centos: $OS8
        image: base-root
    image: "aursu/rpmbuild:${OS8TAG}-build-root"
  centos7repo:
    restart: always
    volumes:
      - rpm7:/home/centos/rpmbuild/RPMS
    build:
      context: createrepo
      args:
        centos: $OS7
    image: aursu/rpmbuild:createrepo
    environment:
      - DELAY_PERIOD=30
  centos6repo:
    restart: always
    volumes:
      - rpm6:/home/centos/rpmbuild/RPMS
    image: aursu/rpmbuild:createrepo
    environment:
      - DELAY_PERIOD=30
  centos8repo:
    restart: always
    volumes:
      - rpm8:/home/centos/rpmbuild/RPMS
    image: aursu/rpmbuild:createrepo
    environment:
      - DELAY_PERIOD=30
  webrepo:
    networks:
      - buildnet
    volumes:
      - rpm6:/home/centos-6/rpmbuild/RPMS
      - rpm7:/home/centos-7/rpmbuild/RPMS
      - rpm8:/home/centos-8/rpmbuild/RPMS
    build:
      context: webrepo
      args:
        centos: $OS8
    image: aursu/rpmbuild:webrepo
    ports:
      - "80:80"

volumes:
  rpm6:
    name: rpm6
  rpm7:
    name: rpm7
  rpm8:
    name: rpm8

networks:
  buildnet:
    name: buildnet
