version: "3.5"
services:
  centos7basesystemd:
    build:
      context: 7/base
      dockerfile: Dockerfile.systemd
    image: aursu/rpmbuild:7-base-systemd
  centos8basesystemd:
    build:
      context: 8/base
      dockerfile: Dockerfile.systemd
    image: aursu/rpmbuild:8-base-systemd
  centos7buildsystemd:
    build:
      context: 7/build
      dockerfile: Dockerfile.systemd
    image: aursu/rpmbuild:7-build-systemd
  centos8buildsystemd:
    build:
      context: 8/build
      dockerfile: Dockerfile.systemd
    image: aursu/rpmbuild:8-build-systemd
  centos7buildtest:
    networks:
      - buildnet
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp=unconfined
    tmpfs:
      - /run
    image: aursu/rpmbuild:7-build-systemd
  centos8buildtest:
    networks:
      - buildnet
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp=unconfined
    tmpfs:
      - /run
    image: aursu/rpmbuild:8-build-systemd

networks:
  buildnet:
    name: buildnet
