version: "3.4"
services:
  centos6base:
    build:
      context: 6/base
    image: rpmbuild:6-base
  centos7base:
    build:
      context: 7/base
    image: rpmbuild:7-base
  centos6build:
    build:
      context: 6/build
    image: rpmbuild:6-build
  centos7build:
    build:
      context: 7/build
    image: rpmbuild:7-build
  centos6repo:
    restart: always
    volumes:
      - rpm6:/home/centos/rpmbuild/RPMS
    build:
      context: createrepo
    image: rpmbuild:createrepo
  centos7repo:
    restart: always
    volumes:
      - rpm7:/home/centos/rpmbuild/RPMS
    build:
      context: createrepo
    image: rpmbuild:createrepo
  webrepo:
    networks:
      - buildnet
    volumes:
      - rpm6:/home/centos-6/rpmbuild/RPMS
      - rpm7:/home/centos-7/rpmbuild/RPMS
    build:
      context: webrepo
    image: rpmbuild:webrepo

volumes:
  rpm6:
    name: rpm6
  rpm7:
    name: rpm7

networks:
  buildnet:
    name: buildnet
