version: "3.5"
services:
  centos6base:
    build:
      context: 6/base
    image: aursu/rpmbuild:6-base
  centos7base:
    build:
      context: 7/base
    image: aursu/rpmbuild:7-base
  centos7baseroot:
    build:
      context: 7/base
      dockerfile: Dockerfile.root
    image: aursu/rpmbuild:7-base-root
  centos6build:
    build:
      context: 6/build
    image: aursu/rpmbuild:6-build
  centos7build:
    build:
      context: 7/build
    image: aursu/rpmbuild:7-build
  centos7buildroot:
    build:
      context: 7/build
      args:
        - image=7-base-root
    image: aursu/rpmbuild:7-build-root
  centos6repo:
    restart: always
    volumes:
      - rpm6:/home/centos/rpmbuild/RPMS
    build:
      context: createrepo
    image: aursu/rpmbuild:createrepo
    environment:
      - DELAY_PERIOD=30
  centos7repo:
    restart: always
    volumes:
      - rpm7:/home/centos/rpmbuild/RPMS
    build:
      context: createrepo
    image: aursu/rpmbuild:createrepo
    environment:
      - DELAY_PERIOD=30
  webrepo:
    networks:
      - buildnet
    volumes:
      - rpm6:/home/centos-6/rpmbuild/RPMS
      - rpm7:/home/centos-7/rpmbuild/RPMS
    build:
      context: webrepo
    image: aursu/rpmbuild:webrepo
    ports:
      - "80:80"

volumes:
  rpm6:
    name: rpm6
  rpm7:
    name: rpm7

networks:
  buildnet:
    name: buildnet
