version: "3.5"
services:
  centos7bintray:
    volumes:
      - rpm7:/home/centos/rpmbuild/RPMS
    build:
      context: createrepo
      dockerfile: Dockerfile.bintray
      args:
        centos: $OS7
    image: aursu/rpmbuild:bintray
  stream8bintray:
    volumes:
      - rpm8stream:/home/centos/rpmbuild/RPMS
    image: aursu/rpmbuild:bintray
  rocky8bintray:
    volumes:
      - rpm8rocky:/home/centos/rpmbuild/RPMS
    image: aursu/rpmbuild:bintray
  stream9bintray:
    volumes:
      - rpm9stream:/home/centos/rpmbuild/RPMS
    image: aursu/rpmbuild:bintray
volumes:
  rpm7:
    name: rpm7
  rpm8stream:
    name: rpm8stream
  rpm9stream:
    name: rpm9stream
  rpm8rocky:
    name: rpm8rocky