version: "3.5"
services:
  centos7base:
    build:
      context: 7/base
      args:
        centos: $OS7
    image: "aursu/rpmbuild:${OS7TAG}-base"
  centos7baseroot:
    build:
      context: 7/base
      dockerfile: Dockerfile.root
      args:
        centos: $OS7
    image: "aursu/rpmbuild:${OS7TAG}-base-root"
  rocky8base:
    build:
      context: 8-rocky/base
      args:
        rocky: $RL8
    image: "aursu/rpmbuild:${RL8TAG}-base"
  rocky8baseroot:
    build:
      context: 8-rocky/base
      dockerfile: Dockerfile.root
      args:
        rocky: $RL8
    image: "aursu/rpmbuild:${RL8TAG}-base-root"
  stream9base:
    build:
      context: 9-stream/base
      args:
        centos: $OS9
    image: "aursu/rpmbuild:${OS9TAG}-base"
  stream9baseroot:
    build:
      context: 9-stream/base
      dockerfile: Dockerfile.root
      args:
        centos: $OS9
    image: "aursu/rpmbuild:${OS9TAG}-base-root"
  centos7rpmb:
    build:
      context: 7/build
      dockerfile: Dockerfile.rpmb
      args:
        centos: $OS7
    image: "aursu/rpmbuild:${OS7TAG}-rpmb"
  centos7docker:
    build:
      context: 7/build
      dockerfile: Dockerfile.docker
      args:
        centos: $OS7
    image: "aursu/rpmbuild:${OS7TAG}-docker"
  centos7rpmbroot:
    build:
      context: 7/build
      dockerfile: Dockerfile.rpmb
      args:
        centos: $OS7
        image: base-root
    image: "aursu/rpmbuild:${OS7TAG}-rpmb-root"
  centos7build:
    build:
      context: 7/build
      args:
        centos: $OS7
    image: "aursu/rpmbuild:${OS7TAG}-build"
  centos7buildroot:
    build:
      context: 7/build
      args:
        centos: $OS7
        image: rpmb-root
    image: "aursu/rpmbuild:${OS7TAG}-build-root"
  rocky8rpmb:
    build:
      context: 8-rocky/build
      dockerfile: Dockerfile.rpmb
      args:
        centos: $RL8
    image: "aursu/rpmbuild:${RL8TAG}-rpmb"
  rocky8docker:
    build:
      context: 8-rocky/build
      dockerfile: Dockerfile.docker
      args:
        centos: $RL8
    image: "aursu/rpmbuild:${RL8TAG}-docker"
  rocky8rpmbroot:
    build:
      context: 8-rocky/build
      dockerfile: Dockerfile.rpmb
      args:
        centos: $RL8
        image: base-root
    image: "aursu/rpmbuild:${RL8TAG}-rpmb-root"
  rocky8build:
    build:
      context: 8-rocky/build
      args:
        rocky: $RL8
    image: "aursu/rpmbuild:${RL8TAG}-build"
  rocky8buildroot:
    build:
      context: 8-rocky/build
      args:
        rocky: $RL8
        image: base-root
    image: "aursu/rpmbuild:${RL8TAG}-build-root"
  stream9build:
    build:
      context: 9-stream/build
      args:
        centos: $OS9
    image: "aursu/rpmbuild:${OS9TAG}-build"
  stream9buildroot:
    build:
      context: 9-stream/build
      args:
        centos: $OS9
        image: base-root
    image: "aursu/rpmbuild:${OS9TAG}-build-root"
  centos7repo:
    restart: always
    volumes:
      - rpm7:/home/centos/rpmbuild/RPMS
    build:
      context: createrepo
      args:
        centos: $OS7
    image: aursu/rpmbuild:createrepo
    environment:
      - DELAY_PERIOD=30
  rocky8repo:
    restart: always
    volumes:
      - rpm8rocky:/home/centos/rpmbuild/RPMS
    image: aursu/rpmbuild:createrepo
    environment:
      - DELAY_PERIOD=30
  stream9repo:
    restart: always
    volumes:
      - rpm9stream:/home/centos/rpmbuild/RPMS
    image: aursu/rpmbuild:createrepo
    environment:
      - DELAY_PERIOD=30
  webrepo:
    networks:
      - buildnet
    volumes:
      - rpm7:/home/centos-7/rpmbuild/RPMS
      - rpm8rocky:/home/rocky-8/rpmbuild/RPMS
      - rpm9stream:/home/stream-9/rpmbuild/RPMS
    build:
      context: webrepo
      args:
        rocky: $RL8
    image: aursu/rpmbuild:webrepo
    ports:
      - "80:80"

volumes:
  rpm7:
    name: rpm7
  rpm8rocky:
    name: rpm8rocky
  rpm9stream:
    name: rpm9stream

networks:
  buildnet:
    name: buildnet
