version: "3"
services:
  rocky8ftptray:
    volumes:
      - rpm8rocky:/home/centos/rpmbuild/RPMS
    build:
      context: createrepo
      dockerfile: Dockerfile.ftptray
      args:
        rocky: $RL8
    image: aursu/rpmbuild:ftptray
  stream9ftptray:
    volumes:
      - rpm9stream:/home/centos/rpmbuild/RPMS
    image: aursu/rpmbuild:ftptray
  rocky9ftptray:
    volumes:
      - rpm9rocky:/home/centos/rpmbuild/RPMS
    image: aursu/rpmbuild:ftptray
  ftprepo:
    volumes:
      - rpm9stream:/home/stream-9/rpmbuild/RPMS
      - rpm8rocky:/home/rocky-8/rpmbuild/RPMS
      - rpm9rocky:/home/rocky-9/rpmbuild/RPMS
    build:
      context: ftprepo
    image: aursu/rpmbuild:ftprepo
    ports:
      - "20-21:20-21"
      - "49152-49160:49152-49160"
    environment:
      - PUBLICADDR
      - PROFTPD_OPTIONS

volumes:
  rpm9stream:
    name: rpm9stream
  rpm8rocky:
    name: rpm8rocky
  rpm9rocky:
    name: rpm9rocky