ARG rocky=8.9.20231119
FROM aursu/rpmbuild:${rocky}-base

USER root
RUN microdnf -y install \
		python39 \
		python3-rpm \
	&& microdnf clean all && rm -rf /var/cache/dnf /var/lib/rpm/__db*

COPY scripts/artifactory.py /usr/local/bin/artifactory.py
RUN chmod 755 /usr/local/bin/artifactory.py

VOLUME ${BUILD_TOPDIR}/RPMS

USER $BUILD_USER

CMD /usr/local/bin/artifactory.py -c ${BUILD_TOPDIR}/RPMS
