FROM aursu/rpmbuild:7-base

COPY scripts/bintray.py /usr/local/bin/bintray.py
RUN chmod 755 /usr/local/bin/bintray.py

VOLUME ${BUILD_TOPDIR}/RPMS

USER $BUILD_USER

ENTRYPOINT ["/usr/local/bin/bintray.py", "${BUILD_TOPDIR}/RPMS"]
CMD ["-c"]
