ARG centos=7.8.2003
FROM aursu/rpmbuild:${centos}-base

USER root
RUN yum -y install \
		ftp \
	&& yum clean all && rm -rf /var/cache/yum /var/lib/rpm/__db*

COPY scripts/ftptray.py /usr/local/bin/ftptray.py
RUN chmod 755 /usr/local/bin/ftptray.py

VOLUME ${BUILD_TOPDIR}/RPMS

USER $BUILD_USER

CMD /usr/local/bin/ftptray.py -c ${BUILD_TOPDIR}/RPMS
