ARG centos=7.9.2009
FROM aursu/rpmbuild:${centos}-base

COPY scripts/bintray.py /usr/local/bin/bintray.py
RUN chmod 755 /usr/local/bin/bintray.py

VOLUME ${BUILD_TOPDIR}/RPMS

USER $BUILD_USER

CMD /usr/local/bin/bintray.py -c ${BUILD_TOPDIR}/RPMS
