services:
  rocky10repo:
    restart: always
    volumes:
      - rpm10rocky:/home/centos/rpmbuild/RPMS
    build:
      context: .
      args:
        rocky: $RL10
    image: aursu/rpmbuild:createrepo
    environment:
      - DELAY_PERIOD=30
  rocky8bintray:
    volumes:
      - rpm8rocky:/home/centos/rpmbuild/RPMS
    build:
      context: .
      dockerfile: Dockerfile.bintray
      args:
        rocky: $RL8
    image: aursu/rpmbuild:bintray
  rocky8ftptray:
    volumes:
      - rpm8rocky:/home/centos/rpmbuild/RPMS
    build:
      context: .
      dockerfile: Dockerfile.ftptray
      args:
        rocky: $RL8
    image: aursu/rpmbuild:ftptray
  rocky10refresh:
    volumes:
      - rpm10rocky:/home/centos/rpmbuild/RPMS
    build:
      context: .
      dockerfile: Dockerfile.refresh
    image: aursu/rpmbuild:refresh
  rocky10cleanup:
    volumes:
      - rpm10rocky:/home/centos/rpmbuild/RPMS
    environment:
      - REFRESH_ACTION=cleanup
    image: aursu/rpmbuild:refresh

volumes:
  rpm10rocky:
    name: rpm10rocky
  rpm8rocky:
    name: rpm8rocky