ARG rocky=8.10.20240528
FROM aursu/rpmbuild:${rocky}-base

USER root
RUN microdnf -y install \
		ftp \
		python39 \
		python39-rpm \
	&& microdnf clean all && rm -rf /var/cache/yum /var/lib/rpm/__db*

COPY scripts/ftptray.py /usr/local/bin/ftptray.py
RUN chmod 755 /usr/local/bin/ftptray.py

VOLUME ${BUILD_TOPDIR}/RPMS

USER $BUILD_USER

CMD /usr/local/bin/ftptray.py -c ${BUILD_TOPDIR}/RPMS
