ARG rocky=8.9.20231119
ARG version=2.299.1
FROM aursu/rockylinux:${rocky}-github-runner-${version}

ENV GITHUB_URL=https://github.com/rpmbsys
ENV GITHUB_TOKEN=

VOLUME $RUNNER_HOME

CMD $RUNNER_HOME/config.sh --unattended --url $GITHUB_URL --token $GITHUB_TOKEN --work $RUNNER_HOME/work
