ARG rocky=10.1.20251126
ARG version=2.328.0
FROM aursu/rockylinux:${rocky}-actions-runner-${version}

ENV GITHUB_URL=https://github.com/rpmbsys
ENV GITHUB_TOKEN=

VOLUME $RUNNER_HOME

CMD $RUNNER_HOME/config.sh --unattended --url $GITHUB_URL --token $GITHUB_TOKEN --work $RUNNER_HOME/work
