version: "3"
services:
  stream9refresh:
    volumes:
      - rpm9stream:/home/centos/rpmbuild/RPMS
    image: aursu/rpmbuild:refresh
  rocky8refresh:
    volumes:
      - rpm8rocky:/home/centos/rpmbuild/RPMS
    build:
      context: createrepo
      dockerfile: Dockerfile.refresh
    image: aursu/rpmbuild:refresh
  rocky9refresh:
    volumes:
      - rpm9rocky:/home/centos/rpmbuild/RPMS
    image: aursu/rpmbuild:refresh
  rocky8cleanup:
    volumes:
      - rpm8rocky:/home/centos/rpmbuild/RPMS
    environment:
      - REFRESH_ACTION=cleanup
    image: aursu/rpmbuild:refresh
  stream9cleanup:
    volumes:
      - rpm9stream:/home/centos/rpmbuild/RPMS
    environment:
      - REFRESH_ACTION=cleanup
    image: aursu/rpmbuild:refresh
  rocky9cleanup:
    volumes:
      - rpm9rocky:/home/centos/rpmbuild/RPMS
    environment:
      - REFRESH_ACTION=cleanup
    image: aursu/rpmbuild:refresh

volumes:
  rpm9stream:
    name: rpm9stream
  rpm8rocky:
    name: rpm8rocky
  rpm9rocky:
    name: rpm9rocky