services:
  webrepo:
    networks:
      - buildnet
    volumes:
      - rpm9stream:/home/stream-9/rpmbuild/RPMS
      - rpm10stream:/home/stream-10/rpmbuild/RPMS
      - rpm8rocky:/home/rocky-8/rpmbuild/RP
      - rpm9rocky:/home/rocky-9/rpmbuild/RPMS
      - rpm10rocky:/home/rocky-10/rpmbuild/RPMS
    build:
      context: .
      args:
        rocky: $RL10
    image: aursu/rpmbuild:webrepo
    ports:
      - "80:80"

volumes:
  rpm8rocky:
    name: rpm8rocky
  rpm9rocky:
    name: rpm9rocky
  rpm10rocky:
    name: rpm10rocky
  rpm9stream:
    name: rpm9stream
  rpm10stream:
    name: rpm10stream

networks:
  buildnet:
    name: buildnet
