ARG rocky=10.1.20251126
ARG version=2.330.0
FROM aursu/rockylinux:${rocky}-actions-runner-${version}

ARG name=github-actions-runner
ARG runnergroup=Default
ARG labels="self-hosted,Linux,X64"
ARG work=_work

ENV GITHUB_URL=https://github.com/rpmbsys
# ENV GITHUB_TOKEN=

ENV RUNNER_NAME=$name
ENV RUNNER_GROUP=$runnergroup
ENV RUNNER_LABELS="${labels}"
ENV RUNNER_WORKSPACE=$work

VOLUME $RUNNER_HOME

CMD $RUNNER_ROOT/config.sh --unattended --replace \
    --url $GITHUB_URL \
    --token $GITHUB_TOKEN \
    --name $RUNNER_NAME \
    --runnergroup $RUNNER_GROUP \
    --labels "${RUNNER_LABELS}" \
    --work $RUNNER_WORKSPACE
