services:
  rocky8basesystemd:
    build:
      context: base
      args:
        rocky: $RL8
        image: systemd
    image: "aursu/rpmbuild:${RL8TAG}-base-systemd"
  rocky8rpmbsystemd:
    build:
      context: build
      dockerfile: Dockerfile.rpmb
      args:
        rocky: $RL8
        image: base-systemd
    image: "aursu/rpmbuild:${RL8TAG}-rpmb-systemd"
  rocky8buildsystemd:
    build:
      context: build
      args:
        rocky: $RL8
        image: rpmb-systemd
    image: "aursu/rpmbuild:${RL8TAG}-build-systemd"
  rocky8buildtest:
    networks:
      - buildnet
    privileged: true
    cgroup_parent: docker.slice
    tmpfs:
      - /run
      - /tmp
    image: "aursu/rpmbuild:${RL8TAG}-build-systemd"

networks:
  buildnet:
    name: buildnet
