
services:
  rocky8refresh:
    volumes:
      - rpm8rocky:/home/centos/rpmbuild/RPMS
    image: aursu/rpmbuild:refresh
  rocky8cleanup:
    volumes:
      - rpm8rocky:/home/centos/rpmbuild/RPMS
    environment:
      - REFRESH_ACTION=cleanup
    image: aursu/rpmbuild:refresh

volumes:
  rpm8rocky:
    name: rpm8rocky
