ARG rocky=9.7.20251123
ARG image=scm
FROM ghcr.io/aursu/rockylinux:${rocky}-${image}

LABEL org.opencontainers.image.source=https://github.com/aursu/docker-rpmbuild

ARG builduser=root
ARG buildgroup=root
ARG buildhome=/root

ENV BUILD_USER $builduser
ENV BUILD_HOME $buildhome
ENV BUILD_TOPDIR ${BUILD_HOME}/rpmbuild

# create rpmbuild structure for user root
RUN mkdir -p ${BUILD_TOPDIR}/{RPMS,SOURCES,SPECS,SRPMS} \
    && chown -R $BUILD_USER:$buildgroup ${BUILD_TOPDIR}
